- name: Add nodejs repo key
  become: yes
  apt_key: 
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    state: 'present'

- name: Add nodejs repo 
  become: yes
  apt_repository: 
    repo: "deb https://deb.nodesource.com/node_4.x/ xenial main"
    update_cache: yes

- name: Install some necessary packages
  become: yes
  apt: 
    name: "{{ item }}"
    state: present 
    update_cache: yes
  with_items:
    - git
    - nodejs

- name: Update npm to latest version
  become: yes
  npm:
    name: npm
    global: yes
    state: latest

# This next section fixes an issue with using npm update in docker containers
# which is necessary for a rebuild
# See: https://github.com/npm/npm/issues/9863
- name: Fix issue with using npm update in docker containers. 
  become: yes
  shell: 'cd $(npm root -g)/npm && npm install fs-extra && sed -i -e s/graceful-fs/fs-extra/ -e s/fs\.rename/fs.move/ ./lib/utils/rename.js'
  when: docker_npm_workaround == True
